const TEAMUPS_DATA = {
    "Season 2.5": { // ultron update
        TEAM_UPS: {
            // previous team-ups
            "Spider-Man": ["Squirrel Girl"],
            "Hela": ["Loki", "Thor"],
            "Cloak & Dagger": ["Moon Knight"],
            "Invisible Woman": ["Human Torch", "The Thing", "Mr. Fantastic"],
            "Captain America": ["Winter Soldier"],
            "Adam Warlock": ["Star-Lord", "Mantis"],
            "Hulk": ["Namor"],
            "Iron Fist": ["Luna Snow"],
            "Magik": ["Black Panther"],
            "Emma Frost": ["Psylocke", "Magneto"],
            "Dr. Strange": ["Scarlet Witch"],
            "Storm": ["Human Torch"],
            "Wolverine": ["The Thing", "Hulk"],
            "Groot": ["Jeff the Land Shark", "Rocket Raccoon"],
            // new team-ups
            "Luna Snow": ["Hawkeye"],
            "Jeff the Land Shark": ["Storm"],
            "The Punisher": ["Black Widow"],
            "Iron Man": ["Ultron"],
            "Rocket Raccoon": ["Peni Parker"],
            "Venom": ["Jeff the Land Shark"],
        },
        CHARACTER_ROLES: {
            "Captain America": "tank",
            "Dr. Strange": "tank",
            "Emma Frost": "tank",
            "Groot": "tank",
            "Hulk": "tank",
            "Magneto": "tank",
            "Peni Parker": "tank",
            "The Thing": "tank",
            "Thor": "tank",
            "Venom": "tank",
            "Black Panther": "dps",
            "Black Widow": "dps",
            "Hawkeye": "dps",
            "Hela": "dps",
            "Human Torch": "dps",
            "Iron Fist": "dps",
            "Iron Man": "dps",
            "Magik": "dps",
            "Moon Knight": "dps",
            "Mr. Fantastic": "dps",
            "Namor": "dps",
            "Psylocke": "dps",
            "Squirrel Girl": "dps",
            "Spider-Man": "dps",
            "Star-Lord": "dps",
            "The Punisher": "dps",
            "Winter Soldier": "dps",
            "Wolverine": "dps",
            "Scarlet Witch": "dps",
            "Storm": "dps",
            "Adam Warlock": "healer",
            "Cloak & Dagger": "healer",
            "Invisible Woman": "healer",
            "Jeff the Land Shark": "healer",
            "Loki": "healer",
            "Ultron": "healer",
            "Luna Snow": "healer",
            "Mantis": "healer",
            "Rocket Raccoon": "healer"
        },
        HEROES: {
            tank: ['Captain America', 'Dr. Strange', 'Emma Frost', 'Groot', 'Hulk', 'Magneto', 'Peni Parker', 'The Thing', 'Thor', 'Venom'],
            dps: ['Black Panther', 'Black Widow', 'Hawkeye', 'Hela', 'Human Torch', 'Iron Fist', 'Iron Man', 'Magik', 'Moon Knight', 'Mr. Fantastic', 'Namor', 'Psylocke', 'Scarlet Witch', 'Squirrel Girl', 'Spider-Man', 'Star-Lord', 'Storm', 'The Punisher', 'Winter Soldier', 'Wolverine'],
            healer: ['Adam Warlock', 'Cloak & Dagger', 'Invisible Woman', 'Jeff the Land Shark', 'Loki', 'Luna Snow', 'Mantis', 'Rocket Raccoon', "Ultron"]
        }
    },
    "Season 2": {
        TEAM_UPS: {
            // old team-ups
            "Rocket Raccoon": ["The Punisher"],
            "Venom": ["Spider-Man", "Peni Parker"],
            "Spider-Man": ["Squirrel Girl"],
            "Hela": ["Loki", "Thor"],
            "Cloak & Dagger": ["Moon Knight"],
            "Hawkeye": ["Black Widow"],
            "Groot": ["Jeff the Land Shark", "Rocket Raccoon"],
            "Invisible Woman": ["Human Torch", "The Thing", "Mr. Fantastic"],
            "Adam Warlock": ["Star-Lord", "Mantis"],
            "Luna Snow": ["Jeff the Land Shark"],
            "Iron Fist": ["Luna Snow"],
            "Magik": ["Black Panther"],
            "Storm": ["Human Torch"],
            // new team-ups
            "Hulk": ["Namor", "Iron Man"],
            "Captain America": ["Winter Soldier"],
            "Dr. Strange": ["Scarlet Witch"],
            "Wolverine": ["The Thing", "Hulk"],
            "Emma Frost": ["Psylocke", "Magneto"],
        },
        HEROES: {
            tank: ['Captain America', 'Dr. Strange', 'Emma Frost', 'Groot', 'Hulk', 'Magneto', 'Peni Parker', 'The Thing', 'Thor', 'Venom'],
            dps: ['Black Panther', 'Black Widow', 'Hawkeye', 'Hela', 'Human Torch', 'Iron Fist', 'Iron Man', 'Magik', 'Moon Knight', 'Mr. Fantastic', 'Namor', 'Psylocke', 'Scarlet Witch', 'Squirrel Girl', 'Spider-Man', 'Star-Lord', 'Storm', 'The Punisher', 'Winter Soldier', 'Wolverine'],
            healer: ['Adam Warlock', 'Cloak & Dagger', 'Invisible Woman', 'Jeff the Land Shark', 'Loki', 'Luna Snow', 'Mantis', 'Rocket Raccoon']
        },
        CHARACTER_ROLES: {
            "Captain America": "tank",
            "Dr. Strange": "tank",
            "Emma Frost": "tank",
            "Groot": "tank",
            "Hulk": "tank",
            "Magneto": "tank",
            "Peni Parker": "tank",
            "The Thing": "tank",
            "Thor": "tank",
            "Venom": "tank",
            "Black Panther": "dps",
            "Black Widow": "dps",
            "Hawkeye": "dps",
            "Hela": "dps",
            "Human Torch": "dps",
            "Iron Fist": "dps",
            "Iron Man": "dps",
            "Magik": "dps",
            "Moon Knight": "dps",
            "Mr. Fantastic": "dps",
            "Namor": "dps",
            "Psylocke": "dps",
            "Squirrel Girl": "dps",
            "Spider-Man": "dps",
            "Star-Lord": "dps",
            "The Punisher": "dps",
            "Winter Soldier": "dps",
            "Wolverine": "dps",
            "Scarlet Witch": "dps",
            "Storm": "dps",
            "Adam Warlock": "healer",
            "Cloak & Dagger": "healer",
            "Invisible Woman": "healer",
            "Jeff the Land Shark": "healer",
            "Loki": "healer",
            "Luna Snow": "healer",
            "Mantis": "healer",
            "Rocket Raccoon": "healer"
        },
    },
    "Season 1.5": { // Human Torch & The Thing update
        TEAM_UPS: {
            // old team-ups
            "Rocket Raccoon": ["The Punisher", "Winter Soldier"],
            "Venom": ["Spider-Man", "Peni Parker"],
            "Spider-Man": ["Squirrel Girl"],
            "Hela": ["Loki", "Thor"],
            "Cloak & Dagger": ["Moon Knight"],
            "Hawkeye": ["Black Widow"],
            "Groot": ["Jeff the Land Shark", "Rocket Raccoon"],
            "Invisible Woman": ["Human Torch", "The Thing", "Mr. Fantastic"],
            "Adam Warlock": ["Star-Lord", "Mantis"],
            "Luna Snow": ["Jeff the Land Shark", "Namor"],
            "Hulk": ["Iron Man", "Dr. Strange"],
            "Iron Fist": ["Luna Snow"],
            "Magik": ["Black Panther", "Psylocke"],
            "Thor": ["Captain America", "Storm"],
            "Scarlet Witch": ["Magneto"],
            // new team-ups
            "Storm": ["Human Torch"],
            "Wolverine": ["Hulk", "The Thing"]
        },
        HEROES: {
            tank: ['Captain America', 'Dr. Strange', 'Emma Frost', 'Groot', 'Hulk', 'Magneto', 'Peni Parker', 'The Thing', 'Thor', 'Venom'],
            dps: ['Black Panther', 'Black Widow', 'Hawkeye', 'Hela', 'Human Torch', 'Iron Fist', 'Iron Man', 'Magik', 'Moon Knight', 'Mr. Fantastic', 'Namor', 'Psylocke', 'Scarlet Witch', 'Squirrel Girl', 'Spider-Man', 'Star-Lord', 'Storm', 'The Punisher', 'Winter Soldier', 'Wolverine'],
            healer: ['Adam Warlock', 'Cloak & Dagger', 'Invisible Woman', 'Jeff the Land Shark', 'Loki', 'Luna Snow', 'Mantis', 'Rocket Raccoon']
        },
        CHARACTER_ROLES: {
            "Captain America": "tank",
            "Dr. Strange": "tank",
            "Emma Frost": "tank",
            "Groot": "tank",
            "Hulk": "tank",
            "Magneto": "tank",
            "Peni Parker": "tank",
            "The Thing": "tank",
            "Thor": "tank",
            "Venom": "tank",
            "Black Panther": "dps",
            "Black Widow": "dps",
            "Hawkeye": "dps",
            "Hela": "dps",
            "Human Torch": "dps",
            "Iron Fist": "dps",
            "Iron Man": "dps",
            "Magik": "dps",
            "Moon Knight": "dps",
            "Mr. Fantastic": "dps",
            "Namor": "dps",
            "Psylocke": "dps",
            "Squirrel Girl": "dps",
            "Spider-Man": "dps",
            "Star-Lord": "dps",
            "The Punisher": "dps",
            "Winter Soldier": "dps",
            "Wolverine": "dps",
            "Scarlet Witch": "dps",
            "Storm": "dps",
            "Adam Warlock": "healer",
            "Cloak & Dagger": "healer",
            "Invisible Woman": "healer",
            "Jeff the Land Shark": "healer",
            "Loki": "healer",
            "Luna Snow": "healer",
            "Mantis": "healer",
            "Rocket Raccoon": "healer"
        },
    },
    "Season 1": { // Vanilla + Invisible Woman & Mr. Fantastic
        TEAM_UPS: {
            // vanilla team-ups
            "Rocket Raccoon": ["The Punisher", "Winter Soldier"],
            "Venom": ["Spider-Man", "Peni Parker"],
            "Spider-Man": ["Squirrel Girl"],
            "Hela": ["Loki", "Thor"],
            "Cloak & Dagger": ["Moon Knight"],
            "Hawkeye": ["Black Widow"],
            "Groot": ["Jeff the Land Shark", "Rocket Raccoon"],
            "Adam Warlock": ["Star-Lord", "Mantis"],
            "Hulk": ["Iron Man", "Dr. Strange"],
            "Iron Fist": ["Luna Snow"],
            "Luna Snow": ["Jeff the Land Shark", "Namor"],
            "Magik": ["Black Panther", "Psylocke"],
            "Thor": ["Captain America", "Storm"],
            "Scarlet Witch": ["Magneto"],
            "Wolverine": ["Hulk"],
            // new team-ups
            "Invisible Woman": ["Mr. Fantastic"],
        },
        HEROES: {
            tank: ['Captain America', 'Dr. Strange', 'Emma Frost', 'Groot', 'Hulk', 'Magneto', 'Peni Parker', 'Thor', 'Venom'],
            dps: ['Black Panther', 'Black Widow', 'Hawkeye', 'Hela', 'Iron Fist', 'Iron Man', 'Magik', 'Moon Knight', 'Mr. Fantastic', 'Namor', 'Psylocke', 'Scarlet Witch', 'Squirrel Girl', 'Spider-Man', 'Star-Lord', 'Storm', 'The Punisher', 'Winter Soldier', 'Wolverine'],
            healer: ['Adam Warlock', 'Cloak & Dagger', 'Invisible Woman', 'Jeff the Land Shark', 'Loki', 'Luna Snow', 'Mantis', 'Rocket Raccoon']
        },
        CHARACTER_ROLES: {
            "Captain America": "tank",
            "Dr. Strange": "tank",
            "Emma Frost": "tank",
            "Groot": "tank",
            "Hulk": "tank",
            "Magneto": "tank",
            "Peni Parker": "tank",
            "Thor": "tank",
            "Venom": "tank",
            "Black Panther": "dps",
            "Black Widow": "dps",
            "Hawkeye": "dps",
            "Hela": "dps",
            "Iron Fist": "dps",
            "Iron Man": "dps",
            "Magik": "dps",
            "Moon Knight": "dps",
            "Mr. Fantastic": "dps",
            "Namor": "dps",
            "Psylocke": "dps",
            "Squirrel Girl": "dps",
            "Spider-Man": "dps",
            "Star-Lord": "dps",
            "The Punisher": "dps",
            "Winter Soldier": "dps",
            "Wolverine": "dps",
            "Scarlet Witch": "dps",
            "Storm": "dps",
            "Adam Warlock": "healer",
            "Cloak & Dagger": "healer",
            "Invisible Woman": "healer",
            "Jeff the Land Shark": "healer",
            "Loki": "healer",
            "Luna Snow": "healer",
            "Mantis": "healer",
            "Rocket Raccoon": "healer"
        },
    }
};